RazorPagesMovie/RazorPagesMovie/Controllers/JoeController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore.Metadata.Internal;

// For more information on enabling Web API for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860

namespace RazorPagesMovie.Controllers
{
    [Route("api/[controller]")]
    [ApiController]
    public class JoeController : Controller
    {
        // GET: api/<JoeController>
        [HttpGet]
        public IEnumerable<string> Get()
        {
            return new string[] { "value1", "value2" };
        }

        // GET api/<JoeController>/5
        [HttpGet("{id}")]
        public string Get(int id)
        {
            return "value";
        }

        [HttpGet("/myIndex")]
        public ActionResult MyIndex()
        {

            return View();

        }



        // POST api/<JoeController>
        [HttpPost]
        public void Post([FromBody] string value)
        {
        }

        // PUT api/<JoeController>/5
        [HttpPut("{id}")]
        public void Put(int id, [FromBody] string value)
        {
        }

        // DELETE api/<JoeController>/5
        [HttpDelete("{id}")]
        public void Delete(int id)
        {
        }
    }
}

RazorPagesMovie/RazorPagesMovie/Pages/Joe/Joe.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore.Metadata.Internal;
using RazorPagesMovie.Models;

namespace RazorPagesMovie.Pages.Joe
{
    public class JoeModel : PageModel
    {

        public JoeModel()
        {
            Person = new Person {Id = Guid.NewGuid().ToString(), Vorname = "John", Nachname = "Doe"};
        }
        
        public Person Person { get; set; }
        public void OnGet()
        {
            //return RedirectToPage("../Movies/Index");
        }

        public IActionResult OnPostJane()
        {

            return RedirectToPage();
        }

        public void OnPostWayne()
        {
            ViewData["jw"] = "Es geht";
            Person.Nachname = "Wayne";
           
        }

        public IActionResult Jane()
        {
            Person.Vorname = "Jane";
            return Page();
        }
    }
}

RazorPagesMovie/RazorPagesMovie/Pages/Joe/Joe.cshtml
@page
@model RazorPagesMovie.Pages.Joe.JoeModel

@{
    ViewData["Title"] = "Create";
    
}
<div>
    <h4>Movie</h4>
    <h1>@ViewData["jw"]</h1>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayFor(model => model.Person.Id)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Person.Vorname)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayFor(model => model.Person.Nachname)
        </dt>

    </dl>
    <form method="post">
        <button asp-page-handler="Jane">Mach Jane</button>
        <button asp-page-handler="Wayne">Mach Wayne</button>
    </form>

</div>